import Category1 from "../../../../assets/UserImages/Category/Cato1.jpg";
import Cook1 from "../../../../assets/UserImages/cook/cook1.png";
import Cook2 from "../../../../assets/UserImages/cook/cook2.jpeg";
import Cook3 from "../../../../assets/UserImages/cook/cook3.jpeg";
import Cook4 from "../../../../assets/UserImages/cook/cook5.jpeg";
import Burger from "../../../../assets/UserImages/burger.jpg";

// Sample data
export const categories = [
  { id: 1, name: "Burgers & Fast", img: Category1 },
  { id: 2, name: "Salads", img: Category1 },
  { id: 3, name: "Pasta & Cousous", img: Category1 },
  { id: 4, name: "Pizza", img: Category1 },
  { id: 5, name: "Breakfast", img: Category1 },
  { id: 6, name: "Soups", img: Category1 },
];

export const cooks = [
  { id: 1, name: "Ram Singh", img: Cook1 , rating: 4.5},
  { id: 2, name: "Sushma Singh", img: Cook2, rating: 4.4 },
  { id: 3, name: "Arpita Thapa", img: Cook3, rating:4.2 },
  { id: 4, name: "Tawas Mom", img: Cook4 , rating:4.9},
  { id: 5, name: "Rupger Ki", img: Cook1, rating:4.3 },
];

export const popularItems = [
  { productId: 1, name: "Cheese Burger", price: "11.88", img: Burger, rating: 4.8, preparationTime: "15-20 min" },
  { productId: 2, name: "Pancake", price: "11.99", img: Burger, rating: 4.7, preparationTime: "10-15 min" },
  { productId: 3, name: "Crispy Sandwich", price: "13.99", img: Burger, rating: 4.6, preparationTime: "15-20 min" },
  { productId: 4, name: "Chicken Wrap", price: "12.99", img: Burger, rating: 4.5, preparationTime: "10-15 min" },
  { productId: 5, name: "Veggie Bowl", price: "10.99", img: Burger, rating: 4.7, preparationTime: "15-20 min" },
  { productId: 6, name: "Steak Sandwich", price: "15.99", img: Burger, rating: 4.9, preparationTime: "20-25 min" },
];
// This file contains the updated cook data with categorized dishes
export const cooksData = [
  {
    id: 1,
    name: "Ram Singh",
    img: "/placeholder.svg?height=300&width=300",
    bio: "Specializing in authentic Indian cuisine with over 15 years of experience. My passion is creating flavorful dishes that bring people together.",
    rating: 4.8,
    reviewCount: 124,
    specialties: ["Indian", "Vegetarian", "Curry"],
    location: "London, UK",
    phone: "+44 123 456 7890",
    email: "ram.singh@example.com",
    workingHours: "Mon-Sat: 9:00 AM - 8:00 PM",
    dishes: [
      {
        id: 101,
        name: "Butter Chicken",
        price: "14.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Tender chicken in a rich, creamy tomato sauce",
        category: "Indian Cuisine",
      },
      {
        id: 102,
        name: "Vegetable Biryani",
        price: "12.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Fragrant rice with mixed vegetables and spices",
        category: "Indian Cuisine",
      },
      {
        id: 103,
        name: "Paneer Tikka",
        price: "10.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Grilled cottage cheese with spices and vegetables",
        category: "Appetizers",
      },
      {
        id: 104,
        name: "Chicken Tikka Masala",
        price: "15.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Grilled chicken pieces in a spiced curry sauce",
        category: "Indian Cuisine",
      },
      {
        id: 105,
        name: "Samosa",
        price: "6.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Crispy pastry filled with spiced potatoes and peas",
        category: "Appetizers",
      },
      {
        id: 106,
        name: "Gulab Jamun",
        price: "7.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Sweet milk dumplings soaked in rose syrup",
        category: "Desserts",
      },
    ],
    reviews: [
      {
        id: 1,
        user: "Sarah M.",
        rating: 5,
        comment: "The best Indian food I've had in London! Authentic flavors and generous portions.",
        date: "2 weeks ago",
      },
      {
        id: 2,
        user: "James P.",
        rating: 4,
        comment: "Delicious food, though delivery was a bit delayed. Would order again.",
        date: "1 month ago",
      },
      {
        id: 3,
        user: "Emma L.",
        rating: 5,
        comment: "Ram's Butter Chicken is to die for! Highly recommend.",
        date: "2 months ago",
      },
    ],
  },
  {
    id: 2,
    name: "Sushma Singh",
    img: "/placeholder.svg?height=300&width=300",
    bio: "I specialize in home-style North Indian cooking with a modern twist. My goal is to bring the authentic taste of my grandmother's kitchen to your table.",
    rating: 4.7,
    reviewCount: 98,
    specialties: ["North Indian", "Street Food", "Desserts"],
    location: "London, UK",
    phone: "+44 123 456 7891",
    email: "sushma.singh@example.com",
    workingHours: "Mon-Sun: 10:00 AM - 9:00 PM",
    dishes: [
      {
        id: 201,
        name: "Chole Bhature",
        price: "13.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Spicy chickpea curry with fried bread",
        category: "North Indian",
      },
      {
        id: 202,
        name: "Aloo Paratha",
        price: "9.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Stuffed potato flatbread with yogurt",
        category: "Breakfast",
      },
      {
        id: 203,
        name: "Gulab Jamun",
        price: "7.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Sweet milk dumplings soaked in rose syrup",
        category: "Desserts",
      },
      {
        id: 204,
        name: "Pani Puri",
        price: "8.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Crispy hollow shells with spicy tangy water",
        category: "Street Food",
      },
      {
        id: 205,
        name: "Samosa Chaat",
        price: "9.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Crushed samosas topped with yogurt, chutneys, and spices",
        category: "Street Food",
      },
      {
        id: 206,
        name: "Rasmalai",
        price: "8.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Soft cheese patties soaked in sweetened, thickened milk",
        category: "Desserts",
      },
    ],
    reviews: [
      {
        id: 1,
        user: "Michael T.",
        rating: 5,
        comment: "Sushma's Chole Bhature is incredible! Authentic taste that reminds me of Delhi.",
        date: "1 week ago",
      },
      {
        id: 2,
        user: "Priya K.",
        rating: 4,
        comment: "Great food, though a bit on the spicy side. The desserts are amazing!",
        date: "3 weeks ago",
      },
      {
        id: 3,
        user: "David W.",
        rating: 5,
        comment: "Best Indian street food in London, hands down!",
        date: "1 month ago",
      },
    ],
  },
  {
    id: 3,
    name: "Arpita Thapa",
    img: "/placeholder.svg?height=300&width=300",
    bio: "I bring the flavors of Nepal and the Himalayas to your doorstep. My cooking focuses on fresh ingredients and traditional techniques passed down through generations.",
    rating: 4.9,
    reviewCount: 87,
    specialties: ["Nepalese", "Himalayan", "Momos"],
    location: "London, UK",
    phone: "+44 123 456 7892",
    email: "arpita.thapa@example.com",
    workingHours: "Tue-Sun: 11:00 AM - 10:00 PM",
    dishes: [
      {
        id: 301,
        name: "Chicken Momos",
        price: "11.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Steamed dumplings filled with spiced chicken",
        category: "Momos",
      },
      {
        id: 302,
        name: "Thukpa",
        price: "13.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Hearty noodle soup with vegetables and meat",
        category: "Soups",
      },
      {
        id: 303,
        name: "Sel Roti",
        price: "8.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Traditional Nepali sweet ring bread",
        category: "Breakfast",
      },
      {
        id: 304,
        name: "Aloo Tama",
        price: "12.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Potato and bamboo shoot curry",
        category: "Nepalese Cuisine",
      },
      {
        id: 305,
        name: "Vegetable Momos",
        price: "10.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Steamed dumplings filled with spiced vegetables",
        category: "Momos",
      },
      {
        id: 306,
        name: "Gundruk Soup",
        price: "9.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Traditional fermented leafy green soup",
        category: "Soups",
      },
    ],
    reviews: [
      {
        id: 1,
        user: "Lisa R.",
        rating: 5,
        comment: "The momos are out of this world! Authentic Nepalese flavors.",
        date: "3 days ago",
      },
      {
        id: 2,
        user: "Tom H.",
        rating: 5,
        comment: "Arpita's Thukpa is perfect for cold London days. So comforting!",
        date: "2 weeks ago",
      },
      {
        id: 3,
        user: "Anita S.",
        rating: 4,
        comment: "Delicious food with great variety. The Sel Roti is a must-try!",
        date: "1 month ago",
      },
    ],
  },
  {
    id: 4,
    name: "Tawas Mom",
    img: "/placeholder.svg?height=300&width=300",
    bio: "I specialize in Filipino home cooking, bringing the vibrant flavors of the Philippines to London. My dishes are a blend of Spanish, American, and Asian influences.",
    rating: 4.6,
    reviewCount: 76,
    specialties: ["Filipino", "Asian Fusion", "BBQ"],
    location: "London, UK",
    phone: "+44 123 456 7893",
    email: "tawas.mom@example.com",
    workingHours: "Wed-Mon: 12:00 PM - 9:00 PM",
    dishes: [
      {
        id: 401,
        name: "Chicken Adobo",
        price: "13.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Chicken marinated in vinegar, soy sauce, and spices",
        category: "Filipino Classics",
      },
      {
        id: 402,
        name: "Pancit Bihon",
        price: "11.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Stir-fried rice noodles with meat and vegetables",
        category: "Noodles",
      },
      {
        id: 403,
        name: "Lechon Kawali",
        price: "15.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Crispy deep-fried pork belly",
        category: "Filipino Classics",
      },
      {
        id: 404,
        name: "Halo-Halo",
        price: "8.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Mixed dessert with shaved ice, fruits, and sweet beans",
        category: "Desserts",
      },
      {
        id: 405,
        name: "Sinigang",
        price: "14.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Sour soup with pork, vegetables, and tamarind",
        category: "Soups",
      },
      {
        id: 406,
        name: "Lumpia",
        price: "9.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Filipino spring rolls with meat and vegetables",
        category: "Appetizers",
      },
    ],
    reviews: [
      {
        id: 1,
        user: "Carlos M.",
        rating: 5,
        comment: "Finally found authentic Filipino food in London! The Adobo is just like my grandmother's.",
        date: "1 week ago",
      },
      {
        id: 2,
        user: "Jenny K.",
        rating: 4,
        comment: "Great flavors and generous portions. The Halo-Halo is a perfect dessert!",
        date: "3 weeks ago",
      },
      {
        id: 3,
        user: "Mark L.",
        rating: 5,
        comment: "The Lechon Kawali is crispy perfection. Will definitely order again!",
        date: "1 month ago",
      },
    ],
  },
  {
    id: 5,
    name: "Rupger Ki",
    img: "/placeholder.svg?height=300&width=300",
    bio: "I bring the rich flavors of Tibet and the Himalayas to your table. My cooking emphasizes organic ingredients and traditional methods that have been used for centuries.",
    rating: 4.7,
    reviewCount: 65,
    specialties: ["Tibetan", "Himalayan", "Vegetarian"],
    location: "London, UK",
    phone: "+44 123 456 7894",
    email: "rupger.ki@example.com",
    workingHours: "Mon-Sat: 10:00 AM - 8:00 PM",
    dishes: [
      {
        id: 501,
        name: "Beef Momos",
        price: "12.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Steamed dumplings with spiced beef filling",
        category: "Momos",
      },
      {
        id: 502,
        name: "Thenthuk",
        price: "13.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Hand-pulled noodle soup with vegetables",
        category: "Soups",
      },
      {
        id: 503,
        name: "Sha Phaley",
        price: "11.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Bread stuffed with seasoned beef and cabbage",
        category: "Tibetan Specialties",
      },
      {
        id: 504,
        name: "Butter Tea",
        price: "4.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Traditional Tibetan tea made with butter and salt",
        category: "Beverages",
      },
      {
        id: 505,
        name: "Tingmo",
        price: "7.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Steamed bread rolls, perfect for dipping in curries",
        category: "Tibetan Specialties",
      },
      {
        id: 506,
        name: "Vegetable Momos",
        price: "11.99",
        img: "/placeholder.svg?height=200&width=300",
        description: "Steamed dumplings with mixed vegetable filling",
        category: "Momos",
      },
    ],
    reviews: [
      {
        id: 1,
        user: "Nina P.",
        rating: 5,
        comment: "The momos are incredible! So flavorful and perfectly cooked.",
        date: "2 weeks ago",
      },
      {
        id: 2,
        user: "Robert J.",
        rating: 4,
        comment: "Authentic Tibetan cuisine that's hard to find elsewhere in London.",
        date: "1 month ago",
      },
      {
        id: 3,
        user: "Sophie T.",
        rating: 5,
        comment: "The Thenthuk is perfect for cold days. So comforting and delicious!",
        date: "2 months ago",
      },
    ],
  },
]

