
import Category1 from "../../../../assets/UserImages/Category/Cato1.jpg"
import Burger from "../../../../assets/UserImages/burger.jpg"
import Pancake from "../../../../assets/UserImages/Pancake.png";
export const foodItemsData = [
    {
      id: 1,
      name: "Cheese Burger",
      price: "250",
      img: Burger,
      rating: 4.8,
      reviewCount: 124,
      category: "Burgers & Fast",
      cook: { id: 1, name: "Ram Singh", img: "/placeholder.svg?height=100&width=100" },
      description:
        "Our signature cheese burger features a juicy beef patty, melted cheddar cheese, fresh lettuce, tomato, and our special sauce, all served on a toasted brioche bun.",
      ingredients: [
        "Beef patty",
        "Cheddar cheese",
        "Lettuce",
        "Tomato",
        "Onion",
        "Pickles",
        "Special sauce",
        "Brioche bun",
      ],
      nutritionalInfo: {
        calories: 650,
        protein: "35g",
        carbs: "48g",
        fat: "32g",
        sodium: "980mg",
      },
      preparationTime: "15-20 min",
      spicyLevel: "Mild",
      isVegetarian: false,
      allergens: ["Gluten", "Dairy", "Egg"],
      tags: ["Burger", "Beef", "Cheese", "Fast Food"],
      reviews: [
        {
          id: 1,
          user: "Sarah M.",
          rating: 5,
          comment: "Best burger I've had in a long time! The patty was juicy and the cheese was perfectly melted.",
          date: "2 weeks ago",
        },
        {
          id: 2,
          user: "James P.",
          rating: 4,
          comment: "Really good burger, though I wish it had a bit more sauce. Will order again!",
          date: "1 month ago",
        },
        {
          id: 3,
          user: "Emma L.",
          rating: 5,
          comment: "The special sauce makes this burger stand out. Absolutely delicious!",
          date: "2 months ago",
        },
      ],
      relatedItems: [2, 3, 6],
    },
    {
      id: 2,
      name: "Pancake",
      price: "150",
      img: Pancake,
      rating: 4.7,
      reviewCount: 98,
      category: "Breakfast",
      cook: { id: 2, name: "Sushma Singh", img: "/placeholder.svg?height=100&width=100" },
      description:
        "Fluffy pancakes served with maple syrup, fresh berries, and a dusting of powdered sugar. Perfect for a sweet breakfast treat.",
      ingredients: ["Flour", "Eggs", "Milk", "Sugar", "Baking powder", "Butter", "Maple syrup", "Mixed berries"],
      nutritionalInfo: {
        calories: 520,
        protein: "12g",
        carbs: "78g",
        fat: "18g",
        sodium: "450mg",
      },
      preparationTime: "10-15 min",
      spicyLevel: "None",
      isVegetarian: true,
      allergens: ["Gluten", "Dairy", "Egg"],
      tags: ["Breakfast", "Sweet", "Pancakes"],
      reviews: [
        {
          id: 1,
          user: "Michael T.",
          rating: 5,
          comment: "These pancakes are so fluffy and delicious! The berries add a perfect touch.",
          date: "1 week ago",
        },
        {
          id: 2,
          user: "Priya K.",
          rating: 4,
          comment: "Great pancakes, though I'd love more maple syrup on the side.",
          date: "3 weeks ago",
        },
        {
          id: 3,
          user: "David W.",
          rating: 5,
          comment: "Best pancakes in town! My kids love them too.",
          date: "1 month ago",
        },
      ],
      relatedItems: [1, 3, 5],
    },
    {
      id: 3,
      name: "Crispy Sandwich",
      price: "200",
      img: Burger,
      rating: 4.6,
      reviewCount: 87,
      category: "Burgers & Fast",
      cook: { id: 3, name: "Arpita Thapa", img: "/placeholder.svg?height=100&width=100" },
      description:
        "A crispy chicken sandwich with fresh lettuce, tomato, pickles, and our homemade mayo, all served on a toasted artisan roll.",
      ingredients: ["Crispy chicken breast", "Lettuce", "Tomato", "Pickles", "Homemade mayo", "Artisan roll"],
      nutritionalInfo: {
        calories: 580,
        protein: "32g",
        carbs: "52g",
        fat: "28g",
        sodium: "890mg",
      },
      preparationTime: "15-20 min",
      spicyLevel: "Medium",
      isVegetarian: false,
      allergens: ["Gluten", "Egg"],
      tags: ["Sandwich", "Chicken", "Crispy"],
      reviews: [
        {
          id: 1,
          user: "Lisa R.",
          rating: 5,
          comment: "The chicken is so crispy and the homemade mayo is amazing!",
          date: "3 days ago",
        },
        {
          id: 2,
          user: "Tom H.",
          rating: 5,
          comment: "Perfect sandwich for lunch. The bread is fresh and the chicken is juicy inside.",
          date: "2 weeks ago",
        },
        {
          id: 3,
          user: "Anita S.",
          rating: 4,
          comment: "Delicious sandwich, though a bit messy to eat. Worth it though!",
          date: "1 month ago",
        },
      ],
      relatedItems: [1, 2, 4],
    },
    {
      id: 4,
      name: "Chicken Wrap",
      price: "300",
      img: Burger,
      rating: 4.5,
      reviewCount: 76,
      category: "Burgers & Fast",
      cook: { id: 4, name: "Tawas Mom", img: "/placeholder.svg?height=100&width=100" },
      description:
        "Grilled chicken, fresh vegetables, and creamy sauce wrapped in a soft tortilla. A perfect on-the-go meal that's both healthy and delicious.",
      ingredients: [
        "Grilled chicken",
        "Mixed greens",
        "Tomato",
        "Cucumber",
        "Red onion",
        "Creamy sauce",
        "Soft tortilla",
      ],
      nutritionalInfo: {
        calories: 480,
        protein: "28g",
        carbs: "45g",
        fat: "22g",
        sodium: "720mg",
      },
      preparationTime: "10-15 min",
      spicyLevel: "Mild",
      isVegetarian: false,
      allergens: ["Gluten", "Dairy"],
      tags: ["Wrap", "Chicken", "Healthy"],
      reviews: [
        {
          id: 1,
          user: "Carlos M.",
          rating: 5,
          comment: "This wrap is perfect for lunch! Fresh ingredients and the sauce is delicious.",
          date: "1 week ago",
        },
        {
          id: 2,
          user: "Jenny K.",
          rating: 4,
          comment: "Great wrap, though I wish it had a bit more chicken.",
          date: "3 weeks ago",
        },
        {
          id: 3,
          user: "Mark L.",
          rating: 5,
          comment: "The vegetables are so fresh and the chicken is perfectly seasoned.",
          date: "1 month ago",
        },
      ],
      relatedItems: [3, 5, 6],
    },
    {
      id: 5,
      name: "Veggie Bowl",
      price: "220",
      img: Burger,
      rating: 4.7,
      reviewCount: 65,
      category: "Salads",
      cook: { id: 5, name: "Rupger Ki", img: "/placeholder.svg?height=100&width=100" },
      description:
        "A nutritious bowl filled with quinoa, roasted vegetables, avocado, and a tangy dressing. Perfect for a healthy and satisfying meal.",
      ingredients: [
        "Quinoa",
        "Roasted sweet potato",
        "Broccoli",
        "Chickpeas",
        "Avocado",
        "Cherry tomatoes",
        "Red onion",
        "Lemon tahini dressing",
      ],
      nutritionalInfo: {
        calories: 420,
        protein: "15g",
        carbs: "58g",
        fat: "18g",
        sodium: "380mg",
      },
      preparationTime: "15-20 min",
      spicyLevel: "None",
      isVegetarian: true,
      allergens: ["Sesame"],
      tags: ["Bowl", "Vegetarian", "Healthy", "Vegan"],
      reviews: [
        {
          id: 1,
          user: "Nina P.",
          rating: 5,
          comment: "This veggie bowl is so flavorful and filling! Perfect healthy lunch option.",
          date: "2 weeks ago",
        },
        {
          id: 2,
          user: "Robert J.",
          rating: 4,
          comment: "Great flavors and textures. The dressing is amazing!",
          date: "1 month ago",
        },
        {
          id: 3,
          user: "Sophie T.",
          rating: 5,
          comment: "As a vegetarian, I appreciate having such a delicious and protein-packed option.",
          date: "2 months ago",
        },
      ],
      relatedItems: [2, 4, 6],
    },
    {
      id: 6,
      name: "Steak Sandwich",
      price: "200",
      img: Burger,
      rating: 4.9,
      reviewCount: 112,
      category: "Burgers & Fast",
      cook: { id: 1, name: "Ram Singh", img: "/placeholder.svg?height=100&width=100" },
      description:
        "Tender slices of grilled steak with caramelized onions, melted cheese, and horseradish sauce on a toasted ciabatta roll. A gourmet sandwich experience.",
      ingredients: [
        "Grilled steak",
        "Caramelized onions",
        "Provolone cheese",
        "Arugula",
        "Horseradish sauce",
        "Ciabatta roll",
      ],
      nutritionalInfo: {
        calories: 680,
        protein: "42g",
        carbs: "48g",
        fat: "36g",
        sodium: "920mg",
      },
      preparationTime: "20-25 min",
      spicyLevel: "Medium",
      isVegetarian: false,
      allergens: ["Gluten", "Dairy"],
      tags: ["Sandwich", "Steak", "Gourmet"],
      reviews: [
        {
          id: 1,
          user: "Alex B.",
          rating: 5,
          comment:
            "This steak sandwich is incredible! The meat is tender and the horseradish sauce adds the perfect kick.",
          date: "5 days ago",
        },
        {
          id: 2,
          user: "Maria C.",
          rating: 5,
          comment: "Worth every penny! The caramelized onions and steak are a perfect combination.",
          date: "2 weeks ago",
        },
        {
          id: 3,
          user: "John D.",
          rating: 4,
          comment: "Delicious sandwich, though a bit messy to eat. The ciabatta bread is perfect for it.",
          date: "1 month ago",
        },
      ],
      relatedItems: [1, 3, 4],
    },
  ]